//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamemisOffLine.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CamemisOffLine.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accout.
        /// </summary>
        public static string acc {
            get {
                return ResourceManager.GetString("acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMINSTRATOR MENU.
        /// </summary>
        public static string Admin_Menu {
            get {
                return ResourceManager.GetString("Admin Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAMEMIS MENU.
        /// </summary>
        public static string Camemis_Menu {
            get {
                return ResourceManager.GetString("Camemis Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string chines {
            get {
                return ResourceManager.GetString("chines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose student.
        /// </summary>
        public static string Cho_Stu {
            get {
                return ResourceManager.GetString("Cho Stu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Schedule.
        /// </summary>
        public static string Cl_Sch {
            get {
                return ResourceManager.GetString("Cl Sch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classrooms.
        /// </summary>
        public static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string daily {
            get {
                return ResourceManager.GetString("daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different file.
        /// </summary>
        public static string Differentfile {
            get {
                return ResourceManager.GetString("Differentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Err {
            get {
                return ResourceManager.GetString("Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate all score bulletins as PDF.
        /// </summary>
        public static string GenaratePdf {
            get {
                return ResourceManager.GetString("GenaratePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password!.
        /// </summary>
        public static string Incorect_User_Pass {
            get {
                return ResourceManager.GetString("Incorect User/Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmer.
        /// </summary>
        public static string kh {
            get {
                return ResourceManager.GetString("kh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutWarning {
            get {
                return ResourceManager.GetString("LogoutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge files.
        /// </summary>
        public static string MergeFile {
            get {
                return ResourceManager.GetString("MergeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make your Selection !.
        /// </summary>
        public static string Message_box_Stu_Result {
            get {
                return ResourceManager.GetString("Message box Stu Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Class.
        /// </summary>
        public static string Message_Box_Stu_Result_Title {
            get {
                return ResourceManager.GetString("Message Box Stu Result Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Month/Semester/Year.
        /// </summary>
        public static string Message_Box_Stu_Result_Title_select_month {
            get {
                return ResourceManager.GetString("Message Box Stu Result Title select month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select School year.
        /// </summary>
        public static string Message_Box_Stu_Result_Title_select_year {
            get {
                return ResourceManager.GetString("Message Box Stu Result Title select year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string monthly {
            get {
                return ResourceManager.GetString("monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result data!.
        /// </summary>
        public static string noresultdata {
            get {
                return ResourceManager.GetString("noresultdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string option {
            get {
                return ResourceManager.GetString("option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Print.
        /// </summary>
        public static string option_print {
            get {
                return ResourceManager.GetString("option print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print monthly result.
        /// </summary>
        public static string Pring_Result {
            get {
                return ResourceManager.GetString("Pring Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print All Subject.
        /// </summary>
        public static string print_all_sub {
            get {
                return ResourceManager.GetString("print all sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Honor Table.
        /// </summary>
        public static string print_honor_table {
            get {
                return ResourceManager.GetString("print honor table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print all Score Bulletins.
        /// </summary>
        public static string Print_Score_Bulletin {
            get {
                return ResourceManager.GetString("Print Score Bulletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print student choice score bulletin.
        /// </summary>
        public static string Print_Score_Choice_Bulletin {
            get {
                return ResourceManager.GetString("Print Score Choice Bulletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string QuseLogout {
            get {
                return ResourceManager.GetString("QuseLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School years.
        /// </summary>
        public static string Sch_Year {
            get {
                return ResourceManager.GetString("Sch Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Enter.
        /// </summary>
        public static string Sco_Enter {
            get {
                return ResourceManager.GetString("Sco Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        public static string semester {
            get {
                return ResourceManager.GetString("semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Attendance.
        /// </summary>
        public static string Staff_Att {
            get {
                return ResourceManager.GetString("Staff Att", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Attendance Report.
        /// </summary>
        public static string Staff_Att_Re {
            get {
                return ResourceManager.GetString("Staff Att Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Academy.
        /// </summary>
        public static string staffacademy {
            get {
                return ResourceManager.GetString("staffacademy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Admin.
        /// </summary>
        public static string staffadmin {
            get {
                return ResourceManager.GetString("staffadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Attendacne.
        /// </summary>
        public static string Stu_Att {
            get {
                return ResourceManager.GetString("Stu Att", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Attendance Report.
        /// </summary>
        public static string Stu_Att_Re {
            get {
                return ResourceManager.GetString("Stu Att Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Detail.
        /// </summary>
        public static string Stu_Detail {
            get {
                return ResourceManager.GetString("Stu Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning result.
        /// </summary>
        public static string Stu_Learn_Result {
            get {
                return ResourceManager.GetString("Stu Learn Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student List.
        /// </summary>
        public static string Stu_List {
            get {
                return ResourceManager.GetString("Stu List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject List.
        /// </summary>
        public static string Sub_List {
            get {
                return ResourceManager.GetString("Sub List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEACHER MENU.
        /// </summary>
        public static string Tea_Menu {
            get {
                return ResourceManager.GetString("Tea Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Schedule.
        /// </summary>
        public static string Tea_Sche {
            get {
                return ResourceManager.GetString("Tea Sche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        public static string telegram {
            get {
                return ResourceManager.GetString("telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Tooltip_top_bar_Close {
            get {
                return ResourceManager.GetString("Tooltip top bar Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Tooltip_top_bar_Max {
            get {
                return ResourceManager.GetString("Tooltip top bar Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Tooltip_top_bar_Menu {
            get {
                return ResourceManager.GetString("Tooltip top bar Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Tooltip_top_bar_Min {
            get {
                return ResourceManager.GetString("Tooltip top bar Min", resourceCulture);
            }
        }
    }
}
